config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  mount LibraryDesign::Engine => "/library_design"

  # Defines the root path route ("/")
  root 'home#index', as: :root
  root 'home#index', as: :home
  
  get 'made-n-laid' => 'made_n_laid#index', as: :made_n_laid_list
  get 'made-n-laid/not-posted-to-bluesky' => 'made_n_laid#not_posted_to_bluesky', as: :made_n_laid_not_posted_to_bluesky
  get 'made-n-laid/not-posted-to-mastodon' => 'made_n_laid#not_posted_to_mastodon', as: :made_n_laid_not_posted_to_mastodon
  
  get 'tweaty-twacker' => 'tweaty_twacker#index', as: :tweaty_twacker_list
  get 'tweaty-twacker/not-posted-to-bluesky' => 'tweaty_twacker#not_posted_to_bluesky', as: :tweaty_twacker_not_posted_to_bluesky
  get 'tweaty-twacker/not-posted-to-mastodon' => 'tweaty_twacker#not_posted_to_mastodon', as: :tweaty_twacker_not_posted_to_mastodon
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/cookies' => 'meta#cookies', as: :meta_cookies
end

app/controllers/tweaty_twacker_controller.rb
class TweatyTwackerController < ApplicationController

  def index
  
    # We get all the treaties.
    @instruments = Treaty.all.order( 'created_at DESC' )
    
    # We set the page meta information.
    @page_title = "Tweaty Twacker"
    @description = "Treaties laid under the Constitutional Reform and Governance Act 2010."
    @rss_url = tweaty_twacker_list_url( :format => 'rss' )
    @crumb << { label: @page_title, url: nil }
    @section = 'tweaty-twacker'
    @subsection = 'all'
  end

  def not_posted_to_bluesky
  
    # We get all the treaties not posted to Bluesky.
    @instruments = Treaty.all.order( 'created_at DESC' ).where( 'posted_to_bluesky IS FALSE' )
    
    # We set the page meta information.
    @page_title = "Tweaty Twacker - not posted to Bluesky"
    @description = "Treaties laid under the Constitutional Reform and Governance Act 2010 not posted to Bluesky."
    @crumb << { label: "Tweaty Twacker", url: tweaty_twacker_list_url }
    @crumb << { label: 'Not posted to Bluesky', url: nil }
    @section = 'tweaty-twacker'
    @subsection = 'not-bluesky'
    
    render :template => 'tweaty_twacker/index'
  end

  def not_posted_to_mastodon
  
    # We get all the treaties not posted to Mastodon.
    @instruments = Treaty.all.order( 'created_at DESC' ).where( 'posted_to_mastodon IS FALSE' )
    
    # We set the page meta information.
    @page_title = "Tweaty Twacker - not posted to Mastodon"
    @description = "Treaties laid under the Constitutional Reform and Governance Act 2010 not posted to Mastodon."
    @crumb << { label: "Tweaty Twacker", url: tweaty_twacker_list_url }
    @crumb << { label: 'Not posted to Mastodon', url: nil }
    @section = 'tweaty-twacker'
    @subsection = 'not-mastodon'
    
    render :template => 'tweaty_twacker/index'
  end
end

app/helpers/tweaty_twacker_helper.rb
module TweatyTwackerHelper
end

app/views/tweaty_twacker/_instrument.html.erb
<li class="list-group-item">
	<%= content_tag( 'h2', link_to( instrument.title, instrument.procedure_browser_url ) ) %>
	<%= content_tag( 'p', "Series citation: #{instrument.series_citation}" ) %>
	<%= content_tag( 'p', "Laid on: #{instrument.laid_on.strftime( $DATE_DISPLAY_FORMAT )}" ) %>
	<%= content_tag( 'p', "Lead organisation: #{instrument.lead_organisation_name}" ) %>
	<%= content_tag( 'p', "Posted to Bluesky: #{instrument.posted_to_bluesky}" ) %>
	<%= content_tag( 'p', "Posted to Mastodon: #{instrument.posted_to_mastodon}" ) %>
	<%= content_tag( 'p', "Imported: #{instrument.created_at.strftime( $DATETIME_DISPLAY_FORMAT )}" ) %>
</li>

app/views/tweaty_twacker/_nav.html.erb
<%= render 'library_design/subnav/subnav' do %>
	<%= link_to( 'All treaties', tweaty_twacker_list_url, :class => 'all' ) %>
	<%= link_to( 'Not posted to Bluesky', tweaty_twacker_not_posted_to_bluesky_url, :class => 'not-bluesky' ) %>
	<%= link_to( 'Not posted to Mastodon', tweaty_twacker_not_posted_to_mastodon_url, :class => 'not-mastodon' ) %>
<% end %>

app/views/tweaty_twacker/index.html.erb
<%= render :partial => 'nav' %>

<%= list_item_count_sentence( 'treaty', @instruments.size ) %>

<%= render :partial => 'library_design/feeds/feeds' %>

<ol class="unnumbered" role="list">
	<%= render :partial => 'instrument', :collection => @instruments %>
</ol>

<details id="sparql">
  <summary>SPARQL queries used by this page</summary>
  <textarea>
	  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
	  PREFIX : <https://id.parliament.uk/schema/>
	  PREFIX id: <https://id.parliament.uk/>
	  SELECT ?Treaty ?treatyTitle ?LeadOrgName ?seriesCitation ?laidDate ?WorkPackageURL  WHERE {
	   ?Treaty a :Treaty;
	           :name ?treatyTitle ;
	           :treatyHasLeadGovernmentOrganisation ?LeadOrg;
	           :workPackagedThingHasWorkPackage ?workPackage;
	           :treatyHasSeriesMembership ?series;
	           :laidThingHasLaying ?laying.
	   ?LeadOrg :name ?LeadOrgName.
	   ?series :seriesItemCitation ?seriesCitation.
	   ?laying :date ?laidDate.
	    ?laying :businessItemHasProcedureStep id:cspzmb6w.  
	    BIND(STR(?workPackage) AS ?workPackageStr)
	    BIND(REPLACE(?workPackageStr, '^.*[/#]', '') AS ?workPackageID)
	    BIND(CONCAT('https://api.parliament.uk/procedure-browser/work-packages/', ?workPackageID) AS ?WorkPackageURL)
	  } order by desc(?laidDate)
  </textarea>
</details>