config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  mount LibraryDesign::Engine => "/library_design"

  # Defines the root path route ("/")
  root 'home#index', as: :root
  root 'home#index', as: :home
  
  get 'made-n-laid' => 'made_n_laid#index', as: :made_n_laid_list
  get 'made-n-laid/not-posted-to-bluesky' => 'made_n_laid#not_posted_to_bluesky', as: :made_n_laid_not_posted_to_bluesky
  get 'made-n-laid/not-posted-to-mastodon' => 'made_n_laid#not_posted_to_mastodon', as: :made_n_laid_not_posted_to_mastodon
  
  get 'tweaty-twacker' => 'tweaty_twacker#index', as: :tweaty_twacker_list
  get 'tweaty-twacker/not-posted-to-bluesky' => 'tweaty_twacker#not_posted_to_bluesky', as: :tweaty_twacker_not_posted_to_bluesky
  get 'tweaty-twacker/not-posted-to-mastodon' => 'tweaty_twacker#not_posted_to_mastodon', as: :tweaty_twacker_not_posted_to_mastodon
  
  get 'meta' => 'meta#index', as: :meta_list
  get 'meta/cookies' => 'meta#cookies', as: :meta_cookies
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @description = 'An application to ingest made as laid statutory instruments and treaties and make them available as RSS and through accounts on both Bluesky and Mastodon.'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= content_tag( 'p', "An application designed to ingest #{link_to( 'made as laid statutory instruments', made_n_laid_list_url)} and #{link_to( 'treaties laid under the Constitutional Reform and Governance Act 2010', tweaty_twacker_list_url)} from the #{link_to( 'procedure SPARQL endpoint', 'https://api.parliament.uk/sparql' )} and make them available as RSS and through accounts on both Bluesky and Mastodon.".html_safe ) %>

<%= content_tag( 'p', "A list of #{link_to( 'all bot accounts made available by the House of Commons Library', 'https://ukparliament.github.io/ontologies/meta/bots/' )} is available on GitHub.".html_safe ) %>